export const strings = [
  'Lorem ipsum odor amet, consectetuer adipiscing elit. Libero pharetra felis in sit himenaeos. Convallis id turpis ornare sollicitudin dui parturient finibus mollis. Lobortis iaculis torquent aliquam malesuada libero hac vivamus? Maximus lacinia semper ante montes donec posuere potenti? Lectus habitasse porta potenti; est orci arcu magna.',

  'Massa condimentum nec metus nulla consequat fames ridiculus. Sit purus mollis felis at est id class nec. Mattis ultrices leo aptent nisi gravida. Hendrerit habitasse lobortis; per luctus phasellus elementum nec quam. Velit senectus hendrerit sociosqu sem ultricies dis tellus. Orci tellus eleifend varius leo ex litora. Lorem tortor dis bibendum luctus enim iaculis. Porta aptent libero pretium ultricies aenean **scelerisque magna**. Ad iaculis nec suspendisse hendrerit, in quisque. Maecenas ultrices potenti fames molestie; etiam laoreet.',

  'Nisi sociosqu conubia vel venenatis ridiculus. Mi amet ultrices ullamcorper enim nulla nec. Suspendisse placerat magna aptent magna himenaeos placerat. Natoque eleifend litora per nostra imperdiet mus hendrerit. Purus curabitur sollicitudin sem gravida sapien felis metus. Taciti suscipit amet euismod ultricies senectus commodo litora. Sociosqu magnis taciti aliquam, inceptos ligula ut per.',

  'Venenatis dolor netus aliquam accumsan at tortor. Erat pretium vestibulum dictum vel curabitur. Duis suscipit dui ipsum risus pretium semper. Nec nam sodales nam tellus ridiculus erat class augue. Facilisis ultrices viverra vestibulum urna aenean cras faucibus. Lectus habitant conubia montes molestie vivamus leo. Porttitor tristique fermentum curabitur varius nulla. Efficitur viverra volutpat cubilia bibendum rutrum facilisi etiam.',
  
  'Inceptos sollicitudin aptent accumsan congue fusce purus luctus conubia? Purus himenaeos molestie aliquet varius diam nascetur, facilisis nulla. Metus elit primis sit consectetur ultricies nascetur. Dis maecenas faucibus fermentum tellus velit. Efficitur bibendum duis varius integer dignissim. Curabitur ultrices mattis tristique curae velit natoque maecenas primis iaculis.',

  'Vehicula orci mus facilisi ac magna luctus nibh felis. Vivamus nibh ac mus nec, sollicitudin taciti. Consequat potenti pharetra curae interdum eros dis imperdiet. Neque hac morbi quis justo cursus placerat. *Placerat porta in etiam magna vitae nam consectetur maecenas.* Integer viverra felis gravida eleifend orci tempus. Duis montes imperdiet magna etiam sem. Netus bibendum parturient aptent augue et magna tellus. Torquent ac habitant magna ac convallis mi? Platea tristique enim, adipiscing conubia penatibus egestas.',

  'Dignissim nascetur varius urna elementum nostra velit sociosqu. Litora pulvinar at nam volutpat viverra ante. Natoque ultricies suspendisse conubia vivamus et volutpat. Senectus quam donec diam facilisis per fames. Facilisi eu bibendum nostra ipsum ligula. Proin natoque habitant porta velit blandit mollis diam. Pulvinar facilisis id penatibus finibus erat euismod.',

  'Ac fermentum rhoncus phasellus faucibus fermentum dolor. Class efficitur diam senectus arcu dolor; eu risus. **Eros magna enim risus** leo interdum interdum facilisi curae. Gravida rutrum suscipit interdum libero praesent ex ultricies sociosqu. Tristique duis nunc mollis elit vivamus accumsan est cras aptent. Fringilla cubilia nascetur mi ultricies lobortis. Torquent netus senectus cubilia tellus primis. Dis penatibus ultricies dignissim fringilla curabitur cras nostra egestas potenti. Orci feugiat cras dictum nam placerat dolor. Luctus pulvinar habitant vel dictum facilisi leo magna sociosqu.',

  'Fringilla iaculis odio imperdiet et taciti lectus sollicitudin. Arcu ante magna natoque gravida condimentum. Rutrum ligula maecenas orci nascetur augue tristique pretium. Laoreet proin sit scelerisque varius nulla pharetra. Integer aliquam quam rutrum donec malesuada egestas hendrerit adipiscing montes. In efficitur augue pretium interdum interdum. Euismod rhoncus vel torquent mi viverra hendrerit venenatis. Duis cras dis, mollis dui dolor eu. Quis sollicitudin aliquet arcu augue diam fusce.',

  'Ut dictum eros pellentesque lacus himenaeos eu aliquam. Hac varius pellentesque id, metus himenaeos turpis nibh. Magna porttitor proin ultrices vitae cursus. Cras quis dictumst ac nunc torquent praesent amet. Magnis penatibus suspendisse platea convallis; vestibulum ultricies nunc. Mauris euismod cubilia litora cras vehicula, at aenean primis. Suscipit lacinia per commodo sapien ultricies. Hac sagittis sit cubilia venenatis imperdiet duis rhoncus himenaeos. Neque potenti faucibus habitasse; lacinia dui himenaeos nec dignissim.'
];
