services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ./.env.database
    expose:
      - '5432'
    ports:
      - "5432:5432"
    labels:
      - "docker.arc.service=postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hankscorpio -d arcdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - arc.net
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_data: