services:
  nginx:
    image: nginx:alpine
    container_name: project-arcturus-nginx-fe-alb
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - bun-web
    networks:
      - arc.net